name: Sast and SCA Scan
on:
  push:
    branches:
      - main  
  pull_request:
    branches: [ "main" ]
jobs:
  gitleaks:
    uses: maarlesh/devops-automation/.github/workflows/main.yml@main
    
  
  
